options:
  logging: CLOUD_LOGGING_ONLY  # fixes the service account logs error

steps:
  # 1️⃣ Build Docker image
  - id: "Build Docker Image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/gcpdevops:latest"
      - "."

  # 2️⃣ Push Docker image
  - id: "Push Docker Image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/gcpdevops:latest"

  # 3️⃣ Deploy to GKE
  - id: "Deploy to GKE"
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - "run"
      - "--filename=gke.yaml"
      - "--image=gcr.io/$PROJECT_ID/gcpdevops:latest"
      - "--location=us-central1-a"
      - "--cluster=gcp-devops-project"
      - "--namespace=gcp-devops-prod"

images:
  - "gcr.io/$PROJECT_ID/gcpdevops:latest"


