steps:
  # Step 0: Authenticate Docker with GCP
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    entrypoint: bash
    args:
      - -c
      - gcloud auth configure-docker --quiet

  # Step 1: Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - gcr.io/$PROJECT_ID/gcpdevops:latest
      - "."

  # Step 2: Push Docker image to Google Container Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/gcpdevops:latest

  # Step 3: Deploy to GKE using updated gke.yaml
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    entrypoint: bash
    args:
      - -c
      - |
        gcloud container clusters get-credentials gcp-devops-project --zone us-central1-a
        kubectl apply -f gke.yaml -n gcp-devops-prod

images:
  - "gcr.io/$PROJECT_ID/gcpdevops:latest"

options:
  logging: CLOUD_LOGGING_ONLY
