steps:
  # Step 0: Authenticate Docker with GCP
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    entrypoint: bash
    args:
      - -c
      - gcloud auth configure-docker --quiet

  # Step 1: Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - gcr.io/$PROJECT_ID/gcpdevops:latest
      - "."

  # Step 2: Push Docker image to Google Container Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/gcpdevops:latest

options:
  logging: CLOUD_LOGGING_ONLY
