steps:
- id: "Build Docker Image"
  name: "gcr.io/cloud-builders/docker"
  args:
  - "build"
  - "-t"
  - "us-central1-docker.pkg.dev/project-da98485c-6f18-42a7-8dd/gcpdevops-repo/gcpdevops:latest"
  - "."

- id: "Push Docker Image"
  name: "gcr.io/cloud-builders/docker"
  args:
  - "push"
  - "us-central1-docker.pkg.dev/project-da98485c-6f18-42a7-8dd/gcpdevops-repo/gcpdevops:latest"

- id: "Deploy to GKE"
  name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - "run"
  - "--filename=gke.yaml"
  - "--image=us-central1-docker.pkg.dev/project-da98485c-6f18-42a7-8dd/gcpdevops-repo/gcpdevops:latest"
  - "--location=us-central1-a"
  - "--cluster=gcp-devops-project"
  - "--namespace=gcp-devops-prod"

images:
- "us-central1-docker.pkg.dev/project-da98485c-6f18-42a7-8dd/gcpdevops-repo/gcpdevops:latest"

options:
  logging: CLOUD_LOGGING_ONLY
