steps:
  # Step 0: Authenticate Docker with GCP
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    entrypoint: bash
    args:
      - -c
      - gcloud auth configure-docker --quiet

  # Step 1: Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - gcr.io/$PROJECT_ID/gcpdevops:latest
      - "."

  # Step 2: Push Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/gcpdevops:latest

  # Step 3: Deploy using kubectl (replaces IMAGE)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    entrypoint: bash
    args:
      - -c
      - |
        # Connect to your GKE cluster
        gcloud container clusters get-credentials gcp-devops-project --zone us-central1-a
        
        # Update deployment with the correct image
        kubectl set image deployment/gcp-devops-gke \
        gcp-devops-gke=gcr.io/$PROJECT_ID/gcpdevops:latest \
        -n gcp-devops-prod
