apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
  namespace: gcp-devops-prod
spec:
  replicas: 2                 # ensures high availability
  selector:
    matchLabels:
      app: gcp-devops
  template:
    metadata:
      labels:
        app: gcp-devops
    spec:
      containers:
      - name: gcpdevops            # must match the container name in cloudbuild.yaml if using set-image
        image: gcr.io/project-da98485c-6f18-42a7-8dd/gcpdevops:latest  # replace with your lowercase project ID
        ports:
        - containerPort: 80
